name: "Building C# projects"
description: "Building C# projects"

inputs: 
  buildConfiguration: 
    description: "Used build configuration"
    required: true
    options: 
      - Release
      - Debug
    default: Release
  buildArguments:
    description: "Arguments for the build"
    required: false
    default: ''
  enabled:
    description: "Enable the steps in this template"
    default: true
    required: true

runs: 
  using: "composite"
  steps:
    - name: Build
      run: dotnet build --no-restore ${{ inputs.buildArguments }} --configuration ${{ inputs.buildConfiguration }}
