name: "Prepare C# Repository"
description: "Setting up the build environment for building C# projects"

inputs: 
  dotNetVersion: 
    description: "The used version of dotnet"
    required: true
    options: 
      - 6.0.x
      - 8.0.x
    default: 6.0.x
  enabled: 
    description: "Enable the steps in this template"
    required: false
    default: true

runs: 
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x        
      if: ${{ inputs.enabled }}
      displayName: "Use .NET Core sdk"
      inputs:
        version: ${{inputs.dotNetVersion}}
        includePreviewVersions: true
    - name: Restore dependencies
      if: ${{ inputs.enabled }}
      run: dotnet restore
