name: "Testing C# projects"
description: "Testing C# projects"

inputs: 
  buildConfiguration:
    description: "Used build configuration"
    type: string
    options: 
      - Release
      - Debug
    default: Release
  reportDestinationPath:
    required: true
    default: "${{ vars.RUNNER_TEMP }}"
  coverletExclude:
    description: "excluded files, that are forwared to coverlet"
    required: false
    default: ''
runs: 
  using: "composite"
  steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{inputs.buildConfiguration}} /p:CoverletOutput=TestResults/Coverage/ /p:CollectCoverage=true /p:ExcludeByFile="${{inputs.coverletExclude}}" "/p:CoverletOutputFormat=\"opencover,Cobertura\""'
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.26
      with:
        reports: "$(Build.SourcesDirectory)/${{inputs.solutionFilePath}}/**/*Tests/TestResults/Coverage/coverage.cobertura.xml"
        targetdir: "${{inputs.reportDestinationPath}}"
        reportTypes: "Cobertura"